# Generated by Django 5.2.7 on 2025-10-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='late_penalized',
            field=models.BooleanField(default=False),
        ),
    ]
